language: python
dist: xenial
sudo: true

python:
  - 3.8

env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1
    - DATABASE_NAME = 'mod_site'
    -DATABASE_USER = 'mod64bits'
    - DATABASE_PASSWORD = 'DjangoTeste'

install:
  - pip install - r requirements.txt
  - cp contrib/env-sample .env


