# Generated by Django 3.1.2 on 2020-11-20 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InformacoesSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('telefone', models.CharField(max_length=30, verbose_name='Telefone')),
                ('endereco', models.TextField(blank=True, null=True, verbose_name='Endereço')),
                ('sobre', models.TextField(verbose_name='Resumo da Empresa')),
                ('img_sobre', models.ImageField(blank=True, null=True, upload_to='infoSite', verbose_name='Imagem Sobre')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='infoSite', verbose_name='Logo')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='FaceBook')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='Twitter')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
            ],
        ),
    ]
