# Generated by Django 3.1.2 on 2020-10-18 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contato', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contato',
            old_name='messagem',
            new_name='menssagem',
        ),
    ]
