# Generated by Django 3.1.2 on 2020-11-30 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.SlugField(unique=True, verbose_name='Nome')),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('descricao_curta', models.TextField(blank=True, null=True, verbose_name='Descrição Curta')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('mes', models.CharField(blank=True, editable=False, max_length=3, null=True, verbose_name='Mes')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('mostra_na_home', models.BooleanField(default=True, verbose_name='Mostra na Pagina Inicial?')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='servicos', verbose_name='Imagem')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicos.categoria', verbose_name='Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='ImagemServico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('imagem', models.ImageField(upload_to='uploads/%Y/%m/%d/', verbose_name='Imagem')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('Projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicos.servico')),
            ],
            options={
                'verbose_name_plural': 'Imagens',
            },
        ),
    ]
