# Generated by Django 3.1.2 on 2020-11-23 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='mes',
            field=models.CharField(blank=True, editable=False, max_length=3, null=True, verbose_name='Mes'),
        ),
    ]
