# Generated by Django 3.1.2 on 2020-10-10 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='mostra_na_home',
            field=models.BooleanField(default=True, verbose_name='Mostra na Pagina Inicial?'),
        ),
    ]
