# Generated by Django 3.1.2 on 2020-11-20 01:09

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Banner Ativo?')),
                ('imagem', models.ImageField(blank=True, help_text='Escolha uma imagem de boa qualidade', null=True, upload_to='banners', verbose_name='Banner')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('Categoria', models.ForeignKey(on_delete=django.db.models.expressions.Case, to='servicos.categoria')),
            ],
        ),
    ]
