# Generated by Django 3.1.2 on 2020-10-15 03:14

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicos', '0004_auto_20201014_0448'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.SlugField(unique=True, verbose_name='Nome')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Banner Ativo?')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('Categoria', models.ForeignKey(on_delete=django.db.models.expressions.Case, to='servicos.categoria')),
            ],
        ),
    ]
