# Generated by Django 3.1.2 on 2020-10-15 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0002_auto_20201015_0316'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='banners', verbose_name='Banner'),
        ),
    ]
