# Generated by Django 3.1.2 on 2020-11-20 01:09

import apps.portifolio.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome')),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('descricao_curta', models.CharField(help_text='Descrição Curta para home', max_length=100, verbose_name='Descrição Curta')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('sobre', models.TextField(blank=True, help_text='Sobre o projeto', null=True, verbose_name='Sobre ')),
                ('home', models.BooleanField(default=True, verbose_name='Mostrar na Home?')),
                ('imagem_de_capa', models.ImageField(upload_to='projetos_img/%Y/%m/%d/', verbose_name='Imagem de Capa')),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('mes', models.CharField(blank=True, editable=False, max_length=3, null=True, verbose_name='Mes')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('Categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portifolio.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('imagem', models.ImageField(upload_to=apps.portifolio.models.renomear_imagem, verbose_name='Imagem')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('Projeto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portifolio.projeto')),
            ],
            options={
                'verbose_name_plural': 'Imagens',
            },
        ),
    ]
