# Generated by Django 3.1.2 on 2020-10-27 15:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='descricao',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Descrição'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projeto',
            name='sobre',
            field=models.TextField(blank=True, help_text='Sobre o projeto', null=True, verbose_name='Sobre '),
        ),
    ]
