# Generated by Django 3.1.2 on 2020-10-27 17:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0002_auto_20201027_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, editable=False, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
