# Generated by Django 3.1.2 on 2020-10-27 23:10

import apps.portifolio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0004_auto_20201027_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='home',
            field=models.BooleanField(default=True, verbose_name='Mostrar na Home?'),
        ),
        migrations.AlterField(
            model_name='imagem',
            name='imagem',
            field=models.ImageField(upload_to=apps.portifolio.models.renomear_imagem, verbose_name='Imagem'),
        ),
    ]
