# Generated by Django 3.1.2 on 2020-10-29 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0005_auto_20201027_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='mes',
            field=models.CharField(blank=True, editable=False, max_length=3, null=True, verbose_name='Mes'),
        ),
    ]
